// Generated by CoffeeScript 1.6.3
(function() {
  var _ArmorPowerUp, _FirepowerPowerUp, _HealthPowerUp, _PowerUp, _PwrUpSpwn, _SpeedPowerUp, _ref, _ref1, _ref2, _ref3, _ref4, _ref5,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.PowerUpSpawner = _PwrUpSpwn = (function(_super) {
    __extends(_PwrUpSpwn, _super);

    function _PwrUpSpwn() {
      _ref = _PwrUpSpwn.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    _PwrUpSpwn.prototype.init = function(pwr_cls) {
      this.active = false;
      this.respawn_time = 20;
      this.time_to_respawn = 0;
      this.power_class = pwr_cls;
      this.image = 'images/spawnpoint.png';
      return this.load_image();
    };

    _PwrUpSpwn.prototype.frame = function() {
      if (!this.active) {
        this.time_to_respawn -= 1;
        if (this.time_to_respawn <= 0) {
          this.unhide();
          this.active = true;
          return this.spawn_power_up();
        }
      }
    };

    _PwrUpSpwn.prototype.consumed = function() {
      this.active = false;
      return this.time_to_respawn = this.respawn_time;
    };

    _PwrUpSpwn.prototype.spawn_power_up = function() {
      var pwr;
      pwr = new this.power_class;
      pwr.init();
      pwr.posx = this.posx;
      pwr.posy = this.posy;
      pwr.spawner = this;
      return pwr.add_to_game();
    };

    return _PwrUpSpwn;

  })(this.GameObject);

  this.PowerUp = _PowerUp = (function(_super) {
    __extends(_PowerUp, _super);

    function _PowerUp() {
      _ref1 = _PowerUp.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    _PowerUp.prototype.init = function() {
      this.bonus = 0;
      this.timeout = 0;
      this.type = '';
      return this.spawner = null;
    };

    _PowerUp.prototype.consume = function(player) {
      player[this.type] += this.bonus;
      this.spawner.consumed();
      return this.remove_from_game();
    };

    _PowerUp.prototype.pre_consume = function(player) {
      return 1;
    };

    _PowerUp.prototype.post_consume = function(player) {
      return 1;
    };

    _PowerUp.prototype.do_timeout = function() {
      return true;
    };

    return _PowerUp;

  })(this.GameObject);

  this.SpeedPowerUp = _SpeedPowerUp = (function(_super) {
    __extends(_SpeedPowerUp, _super);

    function _SpeedPowerUp() {
      _ref2 = _SpeedPowerUp.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    _SpeedPowerUp.prototype.init = function() {
      this.bonus = 1;
      this.timeout = 10;
      this.type = 'speed';
      this.image = 'images/powerups/speed.png';
      return this.load_image();
    };

    _SpeedPowerUp.prototype.consume = function(player) {
      player[this.type] += this.bonus;
      player.active_bonuses.push(this);
      this.spawner.consumed();
      return this.remove_from_game();
    };

    _SpeedPowerUp.prototype.do_timeout = function(player) {
      return player[this.type] -= this.bonus;
    };

    return _SpeedPowerUp;

  })(this.PowerUp);

  this.HealthPowerUp = _HealthPowerUp = (function(_super) {
    __extends(_HealthPowerUp, _super);

    function _HealthPowerUp() {
      _ref3 = _HealthPowerUp.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    _HealthPowerUp.prototype.init = function() {
      this.bonus = 20;
      this.timeout = 0;
      this.type = 'health';
      this.image = 'images/powerups/health.png';
      return this.load_image();
    };

    _HealthPowerUp.prototype.post_consume = function(player) {
      if (player[this.type] > MAX_HEALTH) {
        return player[this.type] = MAX_HEALTH;
      }
    };

    return _HealthPowerUp;

  })(this.PowerUp);

  this.FirepowerPowerUp = _FirepowerPowerUp = (function(_super) {
    __extends(_FirepowerPowerUp, _super);

    function _FirepowerPowerUp() {
      _ref4 = _FirepowerPowerUp.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    _FirepowerPowerUp.prototype.init = function() {
      this.bonus = 2;
      this.timeout = 0;
      this.type = 'damage';
      this.image = 'images/powerups/firepower.png';
      return this.load_image();
    };

    return _FirepowerPowerUp;

  })(this.PowerUp);

  this.ArmorPowerUp = _ArmorPowerUp = (function(_super) {
    __extends(_ArmorPowerUp, _super);

    function _ArmorPowerUp() {
      _ref5 = _ArmorPowerUp.__super__.constructor.apply(this, arguments);
      return _ref5;
    }

    _ArmorPowerUp.prototype.init = function() {
      this.bonus = 5;
      this.timeout = 0;
      this.type = 'armor';
      this.image = 'images/powerups/defend.png';
      return this.load_image();
    };

    return _ArmorPowerUp;

  })(this.PowerUp);

}).call(this);
