// Generated by CoffeeScript 1.6.3
(function() {
  var controllers;

  controllers = angular.module('gai.controllers');

  controllers.controller('GameCtrl', [
    '$scope', '$rootScope', function($scope, $rootScope) {
      var el;
      window.board_width = 630;
      window.board_height = 630;
      window.tile_no_x = 21;
      window.tile_no_y = 21;
      window.tile_width = 30;
      window.tile_height = 30;
      window.rock_count = 100;
      window.frame_step = 300;
      window.powerup_spawn_percent = 15;
      window.max_players = 5;
      window.max_targets = 5;
      window.stats = $("#gamestats");
      el = document.getElementById('gamecanvas');
      window.pinst = new Processing(el, window.sketchProcess);
      window.g = new window.Game;
      return window.g.init_game();
    }
  ]);

}).call(this);
