// Generated by CoffeeScript 1.6.3
(function() {
  var controllers;

  controllers = angular.module('gai.controllers');

  controllers.controller('GameCtrl', [
    '$scope', '$rootScope', '$location', '$anchorScroll', function($scope, $rootScope, $location, $anchorScroll) {
      var el;
      window.board_width = 630;
      window.board_height = 630;
      window.tile_no_x = 21;
      window.tile_no_y = 21;
      window.tile_width = 30;
      window.tile_height = 30;
      window.rock_count = 100;
      window.frame_step = 300;
      window.powerup_spawn_percent = 15;
      window.max_players = 5;
      window.max_targets = 5;
      window.stats = $("#gamestats");
      el = document.getElementById('gamecanvas');
      window.pinst = new Processing(el, window.sketchProcess);
      window.g = new window.Game;
      window.g.init_game();
      pinst.noLoop();
      $scope.is_game_running = false;
      $scope.toggle_game = function() {
        if ($scope.is_game_running) {
          pinst.noLoop();
          return $scope.is_game_running = false;
        } else {
          pinst.loop();
          return $scope.is_game_running = true;
        }
      };
      return $scope.scroll_to = function(id) {
        $location.hash(id);
        return $anchorScroll();
      };
    }
  ]);

}).call(this);
