// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('gai', ['ngRoute', 'gai.controllers']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'partials/game.html',
        controller: 'GameCtrl'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  angular.module('gai.controllers', []);

}).call(this);
