// Generated by CoffeeScript 1.6.3
(function() {
  this.Game = (function() {
    function _Class() {
      console.log("Initialization of Game");
    }

    _Class.prototype.init_game = function(scope) {
      this.game_finished = false;
      this.mrender = new window.MapRenderer;
      this.map = this.mrender.render(tile_no_x, tile_no_y);
      this.scope = scope;
      this.player_counter = 0;
      this.last_move_time = new Date;
      return this.players = new Array;
    };

    _Class.prototype.get_player = function(x) {
      if (x < this.players.length) {
        return this.players[x];
      } else {
        return null;
      }
    };

    _Class.prototype.get_map = function() {
      return this.map;
    };

    _Class.prototype.game_loop = function() {
      var delta, i, now, o, p, _i, _j, _len, _ref, _ref1;
      if (this.game_finished) {
        return true;
      }
      now = new Date;
      delta = now - this.last_move_time;
      if (delta > frame_step) {
        _ref = this.map.game_objects;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          o = _ref[_i];
          o.frame();
        }
        this.last_move_time = now;
        for (i = _j = 0, _ref1 = this.players.length - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          p = this.players[i];
          if (p.state !== PSTATE_DEATH) {
            p.do_action();
          } else {
            p.respawn_timeout -= 1;
            if (p.respawn_timeout <= 0) {
              this.respawn_player(p);
            }
          }
        }
        return this.scope.update_ui();
      }
    };

    _Class.prototype.spawn_new_player = function() {
      var good, p, posx, posy;
      if (this.players.length >= max_players) {
        return;
      }
      p = new Player;
      p.init();
      p.number = this.player_counter;
      p.name = 'Player ' + (this.player_counter++);
      good = false;
      while (!good) {
        posx = get_random_int(0, this.map.width - 1);
        posy = get_random_int(0, this.map.height - 1);
        if (this.map.is_tile_walkable(posx, posy)) {
          if (this.map.is_tile_free(posx, posy)) {
            good = true;
            p.set_position(posx, posy);
          }
        }
      }
      this.players.push(p);
      this.scope.new_event("primary", p.name + " has been spawned");
      return this.map.add_game_object(p);
    };

    _Class.prototype.respawn_player = function(pl) {
      var good, posx, posy;
      pl.set_initial_state();
      good = false;
      while (!good) {
        posx = get_random_int(0, this.map.width - 1);
        posy = get_random_int(0, this.map.height - 1);
        if (this.map.is_tile_walkable(posx, posy)) {
          if (this.map.is_tile_free(posx, posy)) {
            good = true;
            pl.set_position(posx, posy);
          }
        }
      }
      this.scope.new_event("default", pl.name + " has been respawned");
      return this.map.add_game_object(pl);
    };

    _Class.prototype.init_powerup_spawners = function() {
      var good, posx, posy, spawner, type, types, _i, _len, _results;
      types = [HealthPowerUp, FirepowerPowerUp, ArmorPowerUp, SpeedPowerUp];
      _results = [];
      for (_i = 0, _len = types.length; _i < _len; _i++) {
        type = types[_i];
        spawner = new PowerUpSpawner;
        spawner.init(type);
        good = false;
        while (!good) {
          posx = get_random_int(0, this.map.width - 1);
          posy = get_random_int(0, this.map.height - 1);
          if (this.map.is_tile_free(posx, posy)) {
            if (this.map.is_tile_walkable(posx, posy)) {
              if (this.map.get_tile_objects(posx, posy).length === 0) {
                good = true;
                spawner.set_position(posx, posy);
              }
            }
          }
        }
        _results.push(spawner.add_to_game());
      }
      return _results;
    };

    _Class.prototype.player_death = function(pl) {
      var ind;
      ind = $.inArray(pl, this.players);
      this.map.remove_game_object(pl);
      this.scope.new_event("danger", pl.name + " died");
      pl.state = PSTATE_DEATH;
      pl.respawn_timeout = get_random_int(10, 20);
      return this.scope.new_event("default", pl.name + " will respawn in " + pl.respawn_timeout);
    };

    _Class.prototype.player_won = function(pl) {
      this.game_finished = true;
      this.scope.new_event("success", pl.name + " has won the game!!!");
      return this.scope.is_game_running = false;
    };

    return _Class;

  })();

}).call(this);
