// Generated by CoffeeScript 1.6.3
(function() {
  this.init_app = function() {
    return angular.bootstrap(document, ['gai']);
  };

  this.get_random_int = function(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

}).call(this);
